apiVersion: v1
kind: Service
metadata:
  name: hotel-frontend-svc
  namespace: hotel-system
spec:
  selector:
    app: hotel-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
