apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-frontend
  namespace: hotel-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-frontend
  template:
    metadata:
      labels:
        app: hotel-frontend
    spec:
      containers:
        - name: hotel-frontend
          image: sa-saopaulo-1.ocir.io/gr5qlqqo3kg8/hotel-frontend:latest
          ports:
            - containerPort: 80
          env:
            # Opcional: URL del backend interna al cluster
            - name: VITE_API_BASE_URL
              value: "http://hotel-backend-svc.hotel-system.svc.cluster.local:3000"
