version: "3.9"

services:
  backend:
    image: sa-saopaulo-1.ocir.io/gr5qlqqo3kg8/hotel-backend:latest
    container_name: backend
    ports:
      - "3001:3001"

  frontend:
    image: sa-saopaulo-1.ocir.io/gr5qlqqo3kg8/hotel-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
#Así ambos servicios comparten red automáticamente.
networks:
  default:
    external: true
    name: hotel-net

